### ISSUE TITLE
Using  performance and random ??

### ISSUE THREAD

**Issue by matin1099** [A-safarji/vacuum-cleaner-python3#2]
Hi  
I was wondering for "aima  vacuum cleaner agent" in py and found your code. It was good simple to understand for showing students.

I will use it as an example (after some edit for useless and unnecessary section.)  in my TA lecture, of course I'll referencing it to you!

now **down to business**:
1. ### If agent sensing 'room is dirty' , it must clean it! 
      why are you using 'Random.choice'? It will increase  resources usage  while for loop will reduce   it.     line 22 

2. ### What is performance ? ### 
   What define performance for this agent? I wish  i could understand why you using that!        line42

sincerely

**Comment by A-safarji** [comment]
Hi there, 

Thanks for your inquest as you are going to show it for students or any one needs to learn! 

So, the random is to distribute dirt for the square area for the dimension by (1). Then, the agent will visit each to make sure there is dirt or not. But, the performance changes based on how much needed it to clean all random dirt on that dimension [][].

Sorry for replying late and any further questions let me know.  

Regards,
